version: "3"

services:
  reverse-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: reverse-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - ./conf/my_conf.conf:/etc/nginx/conf.d/my_conf.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      HTTPS_METHOD: noredirect
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-proxy
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion:latest
    container_name: acme-companion    
    volumes_from:
      - reverse-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: reverse-proxy
      DEFAULT_EMAIL: login@example.com
    depends_on:
      - reverse-proxy
    networks: 
      - nginx-proxy
    restart: always

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  nginx-proxy:
    external: true
